apiVersion: v1

kind: Service

metadata:

  name: tomcat-service1

  namespace: default

spec:

  type: NodePort

  selector:

    app: tomcat

  ports:

    - port: 80

      protocol: TCP

      targetPort: 8080

      nodePort: 32221